#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright © 2018 Martin Ueding <dev@martin-ueding.de>

import argparse
import mailbox
import re

import dateutil.parser
import pandas as pd


class GermanParserInfo(dateutil.parser.parserinfo):
    '''
    https://stackoverflow.com/a/37485484/653152
    '''
    MONTHS = [("Jan.", "Januar"),
              ("Feb.", "Februar"),
              ("Mar.", "März"),
              ("Apr.", "April"),
              ("Mai.", "Mai"),
              ("Jun.", "Juni"),
              ("Jul.", "Juli"),
              ("Aug.", "August"),
              ("Sep.", "September"),
              ("Okt.", "Oktober"),
              ("Nov.", "November"),
              ("Dez.", "Dezember"),
             ]


def get_body(message):
    '''
    https://stackoverflow.com/a/31489271/653152
    '''
    body = None
    if message.is_multipart():
        for part in message.walk():
            if part.is_multipart():
                for subpart in part.walk():
                    if subpart.get_content_type() == 'text/plain':
                        body = subpart.get_payload(decode = True)
            elif part.get_content_type() == 'text/plain':
                body = part.get_payload(decode = True)
    elif message.get_content_type() == 'text/plain':
        body = message.get_payload(decode = True)
    return body


def main():
    options = _parse_args()

    license_plate_pattern = re.compile(options.license_plate_pattern)
    date_pattern = re.compile(options.date_pattern)
    location_pattern = re.compile(options.location_pattern)
    infraction_pattern = re.compile(options.infraction_pattern)

    parser_info = GermanParserInfo()

    events = []

    for path in options.path:
        print('Parsing', path, '…')
        mbox = mailbox.mbox(path)
        
        for message in mbox:
            if message['Subject'] == options.subject:
                text = get_body(message).decode()

                m = license_plate_pattern.search(text, re.M)
                if not m:
                    continue
                license_plate = m.group(1)

                m = location_pattern.search(text, re.M)
                if not m:
                    continue
                location = m.group(1)

                m = infraction_pattern.search(text, re.M)
                if not m:
                    continue
                infraction = m.group(1)

                m = date_pattern.search(text, re.M)
                if not m:
                    continue
                try:
                    date = dateutil.parser.parse(
                        m.group(1),
                        parserinfo=parser_info,
                    )
                except ValueError:
                    print('Could not parse:', m.group(1))
                    continue

                events.append(dict(license_plate=license_plate,
                                   date=date,
                                   location=location,
                                   infraction=infraction))

                print(' ', license_plate)

    df = pd.DataFrame(events)
    print(df)

    df.to_csv(options.output_path)


def _parse_args():
    '''
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    '''
    parser = argparse.ArgumentParser(description='')

    parser.add_argument('path', nargs='+')
    parser.add_argument(
        '--subject',
        default='Anzeige einer Verkehrsordnungswidrigkeit')
    parser.add_argument(
        '--license-plate-pattern',
        default=r'Kennzeichen: (\w+ \w+\d+)')
    parser.add_argument(
        '--date-pattern',
        default=r'Datum, Uhrzeit: (.+)')
    parser.add_argument(
        '--location-pattern',
        default=r'Ort: (.+)')
    parser.add_argument(
        '--infraction-pattern',
        default=r'Verkehrsordnungswidrigkeit: (.+)')
    parser.add_argument(
        '--output-path',
        default='license_plates.csv')

    options = parser.parse_args()

    return options


if __name__ == '__main__':
    main()
