#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright © 2018 Martin Ueding <dev@martin-ueding.de>

import argparse
import mailbox
import re

import dateutil.parser
import pandas as pd


def get_body(message):
    '''
    https://stackoverflow.com/a/31489271/653152
    '''
    body = None
    if message.is_multipart():
        for part in message.walk():
            if part.is_multipart():
                for subpart in part.walk():
                    if subpart.get_content_type() == 'text/plain':
                        body = subpart.get_payload(decode = True)
            elif part.get_content_type() == 'text/plain':
                body = part.get_payload(decode = True)
    elif message.get_content_type() == 'text/plain':
        body = message.get_payload(decode = True)
    return body


def main():
    options = _parse_args()

    license_plate_pattern = re.compile(options.license_plate_pattern)
    date_pattern = re.compile(options.date_pattern)

    events = []

    for path in options.path:
        print('Parsing', path, '…')
        mbox = mailbox.mbox(path)
        
        for message in mbox:
            if message['Subject'] == options.subject:
                text = get_body(message).decode()

                m = license_plate_pattern.search(text, re.M)
                if not m:
                    continue
                license_plate = m.group(1)

                m = date_pattern.search(text, re.M)
                if not m:
                    continue
                try:
                    date = dateutil.parser.parse(m.group(1))
                except ValueError:
                    print('Could not parse:', m.group(1))
                    continue

                events.append(dict(license_plate=license_plate,
                                   date=date))

                print(' ', license_plate)

    df = pd.DataFrame(events)
    print(df)

    df.to_csv(options.output_path)


def _parse_args():
    '''
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    '''
    parser = argparse.ArgumentParser(description='')

    parser.add_argument('path', nargs='+')
    parser.add_argument(
        '--subject',
        default='Anzeige einer Verkehrsordnungswidrigkeit')
    parser.add_argument(
        '--license-plate-pattern',
        default=r'Kennzeichen: (\w+ \w+\d+)')
    parser.add_argument(
        '--date-pattern',
        default=r'Datum, Uhrzeit: (.+)')
    parser.add_argument(
        '--output-path',
        default='license_plates.csv')

    options = parser.parse_args()

    return options


if __name__ == '__main__':
    main()
